"""Hapus default timestamp dari RekapAbsensi

Revision ID: 32dda1dc7780
Revises: 415df1666a7c
Create Date: 2025-07-22 11:04:05.717624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32dda1dc7780'
down_revision = '415df1666a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_absensi', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_absensi', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
