"""Membuat tabel Mahasiswa dan RekapAbsensi

Revision ID: 415df1666a7c
Revises: 
Create Date: 2025-07-21 13:21:08.950466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415df1666a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('rekap_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekap_absensi')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
